package com.Fumetteria.EsercitazioneFumetteria.models.enums;

public enum Genere {
	ISEKAI, AZIONE, AVVENTURA, 
	COMMEDIA, DRAMMATICO, FANTASY, 
	SCI_FI, CYBERPUNK, SLICE_OF_LIFE, 
	SPOKON, MECHA, HORROR, THRILLER, 
	GIALLO, SOPRANNATURALE, PSICOLOGICO, 
	ROMANTICO, HAREM, STORICO, DISTOPICO, 
	SHONEN, SHOJO, SEINEN, JOSEI, KODOMO, 
	YAOI, YURI
}
